name = "assignment10"
uuid = "769b3496-cf6b-47a0-919f-ea9d0e729bbe"
authors = ["John T. Foster <john.foster@utexas.edu>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
